# Generated by Django 3.1.7 on 2021-04-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210330_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='goose.jpg', upload_to='users/%Y/%m/%d'),
        ),
    ]
