# Generated by Django 3.1.8 on 2021-05-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='image', to='main.ImageFollowers'),
        ),
    ]
