# Generated by Django 3.1.7 on 2021-04-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/preview_size/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/full_size/'),
        ),
    ]
