# Generated by Django 3.1.8 on 2021-04-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210411_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Moderation'), (1, 'Approved')], default=0),
        ),
    ]
