# Generated by Django 3.1.8 on 2021-05-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210503_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='body',
            field=models.TextField(),
        ),
    ]
